### ISSUE TITLE
DoubleTunnelVisualAuthOnVM使用相同用户名认证会导致服务端收包错误

### ISSUE THREAD

**Issue by hbxfwjww** [PassByYou888/ZServer4D#2]
Lazarus版本：2.1.0
FPC版本：3.3.1
网络组件：Synapse & Indy
代码：Examples\20.HelloWorldServerWithLinux + Examples\23.DoubleTunnelVisualAuth + Examples\16.DoubleTunnelAuthOnVM
现象：
将20示例中cmd_Test128MBigStream移植到23+16示例DoubleTunnelVisualAuthOnVM后发现，同时运行2个客户端会导致服务端认为第1个客户端发过来的包有错误，如果UserLogin使用不同用户名登录则正常。

**Comment by PassByYou888** [comment]
现在我并不是随手回复你提的iss,我先检查过代码,并且略微思考过
因为p2pVM是虚拟隧道,等同于VM,你提的问题,其实没有任何影响,p2pVM非常注重稳定性,一但发现非法数据,即会报错.
而你的问题是怎么出现,我分析如下:
双通道服务器只允许一个User在线,同一个id新登录会踢掉原来的user,双通道这时候踢掉的是p2pVm的虚拟连接,并不是物理连接,也就是说物理仍然存在,只是虚拟连接断开了.这时候,在VM中,仍然有残留的粘包数据,而p2pVM已经被认为断线,所以它才会报错.

解决办法1,在双通道TCommunicationFramework_DoubleTunnelClient中,继承ClientDisconnect,截获到vm断线事件中,检查p2pVM是否还在线,如果p2pVM没有断线,断开它.
解决办法2,开辟一个timer事件,在该事件中,通过检查双通道客户端linkOk是否=false,以及物理连接是否=true,如果成立,断开物理连接.

希望你可以帮到你.

by.qq600585

**Comment by hbxfwjww** [comment]
收到，那就是设计如此，并非BUG，我测试使用TCommunicationFramework_DoubleTunnelClient_NoAuth正常，看起来多并发无需认证的场景使用它比较合适。
