### ISSUE TITLE
Consider more permissive license than GPL

### ISSUE THREAD

**Issue by TommiPrami** [PassByYou888/ZServer4D#3]
GPL as license is way too restrictive for commercial use. Also it drive away some users and possible contributors on the project.

On  FPC side  GPL is more than less OK, but on Delphi side GPL is top restrictive for 95% of projects, because it does not allow proper and more free commercial usage of the library.

That does not mean they won't contribute, but more permissive license or dual licensing of your libraries, would attract more people from Delphi user base, which mostly are people who need to be able to link library into closed source application

**Comment by PassByYou888** [comment]
plan
